name: check and publish snapshot Python tarball to PyPi

on:
    push:
      branches-ignore:
        - master
        - version-*
      paths-ignore:
        - README.md

jobs:
  build-job:
    name: Check and publish snapshot tarball to PyPi
    uses: th2-net/.github/.github/workflows/compound-python.yml@python-workflow # FIXME: change to main
    with:
      release-type: development
      python-check-versions: "['3.8', '3.9', '3.10', '3.11', '3.12']"
      scan-safety-args: '-i 70612' # ignore https://data.safetycli.com/v/70612/97c/. Jinja2 library is not used in our code directly.

    secrets:
      pypi-password: ${{ secrets.PYPI_PASSWORD }}
